# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "Next-Gen-Hydro" ]
  pull_request:
    branches: [ "Next-Gen-Hydro" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # You can specify the Flutter version you need
 - name: Cache dependencies
        run: flutter pub get

      - name: Initialize Firebase
        id: initialize_firebase
        run: |
          flutter pub run flutter_native_splash:create
          flutter test --platform=chrome || exit 0
          echo "::set-output name=initialized::true"

      - name: Run Tests
        if: steps.initialize_firebase.outputs.initialized == 'true'
        run: flutter test --no-sound-null-safety

      - name: Build APK
        if: success()  # Only build APK if tests pass
        run: flutter build apk